FROM skobow/docker-gradle-git

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Bundle app source
RUN git clone -b upgrade_netty https://github.com/tombolaltd/Turbine.git

WORKDIR /app/Turbine

EXPOSE 8989

ENTRYPOINT ./gradlew tombolaRun