FROM skobow/docker-gradle-git

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Bundle app source
RUN git clone -b upgrade_netty https://github.com/tombolaltd/Turbine.git

WORKDIR /app/Turbine
RUN ls -a
# Build the solution (using the gradle task)
RUN gradle build

EXPOSE 8989

ENTRYPOINT gradle tombolaRun